# Generated by Django 2.2.5 on 2019-10-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото')),
                ('article', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(max_length=256, verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиента', 'verbose_name_plural': 'Клиенты'},
        ),
    ]
