# Generated by Django 2.2.5 on 2019-11-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191022_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('is_active', 'id'), 'verbose_name': 'товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=64, verbose_name='Почта'),
        ),
    ]
